### ISSUE TITLE
Display login box in popup

### ISSUE THREAD

**Issue by enperezr** [knpuniversity/oauth2-client-bundle#110]
How can I display the login box in a popup instead a redirect to facebook login page? I have read in some others bundles something like in config 
display: popup

**Comment by weaverryan** [comment]
Hi @enperezr!

It's a good question. There are 2 separate ways to "login" with Facebook - either using their JavaScript SDK or doing a manual OAuth2 flow server side (with redirects). This bundle is all about giving you some tools to help with the second, manual OAuth2 flow. Here's a really good article that talks about both approaches, and even how to combine the two of them at the bottom (so that you can use the JavaScript popup, but then pass the access token back to your server): https://www.sammyk.me/best-practice-for-facebook-login-with-the-javascript-sdk-and-php-sdk-v4-1

Cheers!

**Comment by enperezr** [comment]
thank you very much.

2018-07-23 11:05 GMT-04:00 Ryan Weaver <notifications@github.com>:
