### ISSUE TITLE
Fosuserbundle: New user is authenticated after second connect

### ISSUE THREAD

**Issue by vanjaPalpa** [knpuniversity/oauth2-client-bundle#150]
Hi all,

I have some problem with the bundle.

I use Fosuserbundle and knpuniversity/oauth2-client-bundle.

All works perfectly when user already exists in database. But when it's a new user, user was added in database but after redirect, he is not authenticated. After, if you retry to reconnect, all works perfectly and he will authenticated overtime till he is in database.

Thanks for your help.

May be some configuration for Fosuserbundle user provider or something like that

**Comment by weaverryan** [comment]
Hi @vanjaPalpa!

Hmm. My guess is that, for some reason, after the redirect, your user looks "changed". It's kind of a hard thing to explain. But, to see if I'm right, try this:

1) Override the `public function isEqualTo(UserInterface $user)` method in your `User` class and just return true.

2) Try it again! If it works, then i'm correct about the cause. And the problem is that, for some reason, the `isEqualTo` method in FOSUserBundle is returning false (https://github.com/FriendsOfSymfony/FOSUserBundle/blob/5850fba5f65b16ddb293f6635bbb8ac4aa293883/Model/User.php#L562). Make sure all of the fields are set correctly on the new `User` object before returning it from your authenticator (for example, maybe the encoded "password" has not been set yet).

Cheers!
