### ISSUE TITLE
Get List of Clients via ClientRegistry

### ISSUE THREAD

**Issue by solverat** [knpuniversity/oauth2-client-bundle#194]
It would be great to retrieve the list of available clients via the registry. 

Example:

```php

/**
 * @return array
 */
public function getClientKeys()
{
    return array_keys($this->serviceMap);
}
```

This allows us to get a list of all clients in a more generic way (list available connect-links via twig extension or creating a generic route like `connect/{serviceKey}` for example).

I can provide a PR for that if you wish!

Thanks!

**Comment by bocharsky-bw** [comment]
Hey @solverat , thank you for this suggestion! Hm, do you mean a list of all clients available in your application, like those clients you installed in your project? Or list of really _all_ clients that is supported by knpuniversity/oauth2-client-bundle? Because for me the 2st just looks like overkill, I can't think of a project that uses _all_ clients. We have the _full_ list in the README, and I think it's enough to easily find and choose the clients you need, then just coding the implementation. I just can't think of when it's useful on the programmatic level :)

**Comment by solverat** [comment]
Hey @bocharsky-bw. No, just the active ones. All clients wouldn't make any sense at all.

**Comment by bocharsky-bw** [comment]
The idea sounds fine to me in general, but depends on how robust will be its implementation. If it will be helpful for you and nobody against it with strong arguments, I think you can try to send a PR for this
