### ISSUE TITLE
Composer dependencies

### ISSUE THREAD

**Issue by emmanuelballery** [knpuniversity/oauth2-client-bundle#200]
Hi!

"symfony/phpunit-bridge" is listed as required even on non-dev environments. I had a look at the code and I don't catch the necessity. Can someone please tell me why this is not a "require-dev"?

While I'm at it, "symfony/yaml" is not really a direct requirement in dev. I think there is no reference to this lib ; it is used via the "symfony/dependency-injection" only (and is a requirement of this one) ;

Thank you!

**Comment by bocharsky-bw** [comment]
Hey @emmanuelballery, good catch!

Looks like `symfony/phpunit-bridge` was put into `require` section instead of `require-dev` mistakenly in #199 .

About `symfony/yaml` - hm, I don't see we use this component directly in this bundle, but not sure 100%. Probably we can try to remove it and see if tests pass.

Do you want to open a PR to fix this?

**Comment by weaverryan** [comment]
Yea, nice catch! Here's the PR for the issue: #202 

About `symfony/yaml`, this bundle *does* depend on `symfony/dependency-injection`. You're correct that we don't directly need `symfony/yaml`... but basically this would be an issue with `symfony/dependency-injection`, not this bundle (in theory, `symfony/yaml` could be an optional dependency of that library)

**Comment by emmanuelballery** [comment]
Wow, you're fast!

My remark regarding `symfony/yaml` was only for clarification. `symfony/dependency-injection` does depend on `symfony/yaml` ; therefore, as `knpuniversity/oauth2-client-bundle` is not using Yaml directly, it seemed like it was not its concern.

Thank you again!
