### ISSUE TITLE
Connect With Existing Profile

### ISSUE THREAD

**Issue by frederic9583** [knpuniversity/oauth2-client-bundle#207]
Hi. If i have an existing user (registered via classic registration form) and i want to connect the user to facebook - is there any example? 

I'm able to connect my (new) user with your guard example, so far so good.

Should i create a second guard? Is it bad practice to involve a guard, if there is already a logged in user? I also want to avoid duplicate code so i'm wondering how i could achieve this?

**Comment by weaverryan** [comment]
Hey @frederic9583!

Hmm, yea, that seems like a fine approach to me :). I agree that fetching the user in the authenticator "feels" a bit weird, but I can't see a big issue with it. In fact, instead of passing the `_type` flag, I think you could just toggle (in your authenticator) based on whether or not a user is already authenticated. After all, what you *really* care about at this point is:

A) If not logged in, find or create user
B) If logged, just use that user
C) In both cases, then "link" user to this facebook account.

Cheers!

**Comment by frederic9583** [comment]
@weaverryan thanks for your reply. I guess that's the way then!
