### ISSUE TITLE
Scope and Re-access information

### ISSUE THREAD

**Issue by shairyar** [knpuniversity/oauth2-client-bundle#21]
Hi,

I managed to get it to work with Facebook and everything is working perfectly file.

I have 3 questions

**Question 1**

I want to fetch more details of user from Facebook like **user_education_history** and **user_work_history**.

My assumption is that in Controller I need to provide the scope I need for example as following

```
    /**
     * @Route("/connect/facebook", name="connect_facebook")
     */
    public function connectFacebookAction(Request $request)
    {
        // redirect to Facebook
        $facebookClient = $this->get('knpu.oauth2.registry')
            ->getClient('my_facebook_client');

        return $facebookClient->redirect([
            'public_profile', 'email', 'user_education_history', 'user_work_history'
        ]);
    }
```

By giving the scope I do see in facebook permission popup that education and work are listed so I just wanted to confirm if this is the right way?

**Question 2**
Suppose I want to give a button to user which they can use to pull updated work and education history from Facebook or LinkedIn, how is that going to be possible? Is there already a service which we can use for this purpose? An example will really be nice to see how this is going to work.

**Question 3**
I am looking at the tutorial [here](https://github.com/knpuniversity/guard-tutorial/blob/finished/src/AppBundle/Security/FacebookAuthenticator.php#L69)  and when I dump the `$accessToken`, the `refreshToken` is null. If my understanding is right I think I will need the `refreshToken` in case the token expires so how can i get hold of `refreshToken`?

**Comment by weaverryan** [comment]
Hey @shairyar!

**Question 1**: Yep - your code looks totally correct.

**Question 2**: You'll need to save the access token somewhere so you can use it later. But, Facebook  has short-lived tokens, so you'll need to exchange it for a long-lived token (https://github.com/thephpleague/oauth2-facebook#long-lived-access-tokens). So, after you've fetched the access token normally (called `$shortLivedToken) in my example), you would do this:

```php
$client = $this->get('oauth2.registry')
            ->getClient('facebook_main');

$provider = $client->getOAuth2Provider();
// then start following the code in the link
$token = $provider->getLongLivedAccessToken($shortLivedToken);
```

**Question 3**

Facebook doesn't offer refresh tokens... so that's the problem :). There's some more info here: https://github.com/thephpleague/oauth2-facebook#refreshing-a-token. The long-lived token is the best you can do. Eventually you'll need to send them through the authorization process again.

Cheers!

**Comment by weaverryan** [comment]
Hey - closing this now!
