### ISSUE TITLE
"Authentication failed! Did you authorize our app?" and "no 'code' attribute"

### ISSUE THREAD

**Issue by KriBetko** [knpuniversity/oauth2-client-bundle#210]
Hello. I am upgrading from `knpuniversity/oauth2-client-bundle:^1.10` to `^1.30` and `league/oauth2-google: ^1` to `^3` on `symfony/symfony:^3.4(not flex)`and am I having problems.
I updated the controller following the example in README.md, But I get an error "_**Authentication failed! Did you authorize our app?**_". Old code doesn't work either.
Using debug, I found that when get `OAuth2Client`, the `fetchAccessToken` function throws an exception `MissingAuthorizationCodeException` because there is no "_**code**_" in the request attributes. What is the problem?
Thanks.

P.S. `google_client_id` and `google_client_secret` valid and works. I do not give examples of my code, because it is the same as in the example in README.md

**Comment by weaverryan** [comment]
Hi there!

I'm not sure what the problem is. But, the flow should look like this:

1) You redirect the user to Google to authorize your app
2) Google redirects back to your site **with a `?code=`** query parameter (because that's just how OAuth works)
3) The request from (2) is handled by your app - and something in your app is calling `OAuth2Client::fetchAccessToken()`. This method (again, this is just the nature of how OAuth works) looks for the `?code=` query parameter so that it can exchange it with Google for an access token.

So, for some reason, when `fetchAccessToken()` is called, there is no `?code=` on the URL. Check out your "flow" to see what's going on.

Cheers!

**Comment by Alexandre-T** [comment]
In earlier version, with the new OAuth2Authencator, I got this error because the `supports` method of my `GoogleAuthenticator` was too large.

My code was:   `return $request->headers->has('authorization');`

I fix it with:  `return $request->attributes->get('_route') === 'connect_google_check';`

I'm using Sf6.3, ApiPlatform 3
