### ISSUE TITLE
Authenticating with token in header

### ISSUE THREAD

**Issue by andheiberg-gelato** [knpuniversity/oauth2-client-bundle#218]
I have KnpUOAuth2ClientBundle setup with KeyCloak. Authentication is work perfectly with KeyCloak for normal browser requests.

However, I intend to expose API endpoints that need to be authenticated as well. I can't find any documentation on how a API client is supposed to authenticate a requests with a token they have acquired from KeyCloak.

Sending the Authorization header does not appear to do the trick. What am I missing here?

**Comment by weaverryan** [comment]
Hey @andheiberg-gelato!

Sorry for the slow reply. I think what you're looking for is effectively `$accessToken = $client->getAccessToken();`. You would then use the `$accessToken` to make whatever requests you need.

Let me explain that in more detail :). This library helps you *get* the access token (via the OAuth flow). But once it gives you the access token, it does *not* help you use that token to make authenticated requests back to the API that the access token is for. Well, there is one exception to that rule: 

```
$user = $client->fetchUserFromToken($accessToken);
```

The library has this *one* method that helps you use the `$accessToken` to make an authenticated API request to retrieve information about the "user" that the access token is for. But if you need to make *any* other API request, you'll need to do it manually - e.g. via Symfony HTTP Client or Guzzle. The reason is that this library is all about the OAuth flow only. Once you get the access token, it's job is done.

Let me know if that helps!

Cheers!
