### ISSUE TITLE
[question] client_credential grant: how to verify bearer token ?

### ISSUE THREAD

**Issue by floxblah** [knpuniversity/oauth2-client-bundle#247]
Hello,

I'm trying to use guard to protect an API endpoint with keycloak using the client_credentials grant. I set up the oauth2-client-bundle with stevenmaguire/oauth2-keycloak oauth2 Client on my client website and on my api endpoint.

Everything works fine if i use the standard flow so my code and configuration are good in this case but it doesn't work with client_crendtials flow.

On my client website i only use the oauth2-client-bundle to get a bearer token :

I successfully get a bearer token from keycloak using this:
` $this->keycloakClient->getOAuth2Provider()->getAccessToken('client_credentials');`
then i send the request to my API endpoint using the token.
```
$this->httpClient->request('GET',"myApiEndPoint",
[ 'auth_bearer' => $accessToken->getToken(),] );
```

Then i try to protect my API endpoint with guard:
in my controller the request from the client is correctly redirected:

```
  /**
     * @Route("/connect/keycloak", name="connect_keycloak_start")
     */
    public function connectAction(ClientRegistry $clientRegistry)
    {
        $keyCloakClient = $clientRegistry->getClient(KeycloakTokenAuthenticator::KEYCLOAK_CLIENT);
        return $keyCloakClient->redirect([], []);
    }

    /**
     * @Route("/connect/keycloak/check", name="connect_keycloak_check")
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
    {
        // use Guard authenticator
    }
```
My guard authenticator is quiet similar to the example in the oauth2-client-bundle readme and it failed to the  getCredentials step:

```
  public function getCredentials(Request $request)
    {
        return $this->fetchAccessToken($this->getKeycloakClient());
    }
```
I got this message: Authentication failed! Did you authorize our app?

I can't figure out if i there is a mistake in my keycloak configuration or if i must set specials parameters when i redirect to keycloak  on the controller or if i missed something else.

**Comment by weaverryan** [comment]
Hi there!

This bundle is primarily focused on helping you through the "authorization_code" flow. And so, parts of it are hardcoded directly for that - https://github.com/knpuniversity/oauth2-client-bundle/blob/2e54646ae5b1a41bde7985ab1dbdd5cb4ceb0462/src/Client/OAuth2Client.php#L108

I believe this is why it's not working for you. The reason is that, if you're using something like the `client_credentials` flow, then you've already done a lot of work yourself :). But, you should still be able to use the bundle. You can get the underlying Oauth2 provider by calling `$this->getKeycloakClient()->getOAuth2Provider()`. And then, you should be able to call `-> getAccessToken('client_credentials')` on that.

Cheers!
