### ISSUE TITLE
What about api projects without twig?

### ISSUE THREAD

**Issue by bettinz** [knpuniversity/oauth2-client-bundle#256]
Hello, I'm doing an API project with Symfony 5.1 and api-platform.
Usually I'm doing the login process with lexik jwt bundle; now I want to use the login and registration via social. How can I handle that?

Thanks 😄

**Comment by weaverryan** [comment]
Hey @bettinz!

It depends on what your frontend looks like. Are you building a true SPA? Is that one page rendered through Symfony? There's a good chance that, with an SPA, you won't use this bundle. If you want to keep the SPA experience (no reloads), then the OAuth process would take place entirely client-side - you can read it a bit about some options here: https://www.oauth.com/oauth2-servers/single-page-apps/

Ultimately, in JavaScript, you would end up with an "access token". You could then send the access token to some endpoint on the API that authenticates you (i.e. stores some User object in the session or returns some other type of token - like a JWT - that can be used on subsequent requests to authenticate the user).

In both cases, your code would probably use the access token to make a request to the API of the social service to verify it's legit and get some user information. The purpose of this bundle is mostly to GET that access token. Since you will already have it, probably this bundle won't help you.

Good luck!

**Comment by bettinz** [comment]
Hello, sorry for the delay.
This is how I've solved, maybe this can help other users. I'm using an API for a smartphone app.

FacebookController:
- like the tutorial, with `connectCheckAction` empty

FacebookAuthernticator:
- I do everything like check the Facebook ID and the email into the getUser function.

This piece of code return the JWT token on success:
```php
public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return new JsonResponse(['token' => $this->JWTToken->create($token->getUser())]);
    }
```
Since I'm building that API for a SPA and an APP it's better to do this on the API right? Do you have any advice about my implementation?

Thank you for the help 😉

**Comment by weaverryan** [comment]
> This is how I've solved, maybe this can help other users. I'm using an API for a smartphone app

Thanks for sharing :)

> Since I'm building that API for a SPA and an APP it's better to do this on the API right? Do you have any advice about my implementation?

I'm not sure. What is the OAuth "flow" that you decided to use? Are you doing it all on JavaScript and then just sending the access token to the server? 

And what did you mean exactly by this quetion:

> Since I'm building that API for a SPA and an APP it's better to do this on the API right

Cheers!

**Comment by fd6130** [comment]
Hmmm so we can't use this bundle if we building for Android, IOS or Flutter rather than web?
