### ISSUE TITLE
How to check if access token expired, to be refreshed?

### ISSUE THREAD

**Issue by kdefives** [knpuniversity/oauth2-client-bundle#260]
Hello,

I get the user access token from external OAuth2 system during the authentication but the access_token is valid during 2 hours.
**How should I have to check if the user access token is expired or not in order to trig a token refresh?** I do not find documentations about that part :(

I need to check if the token is valid regularly because inside my application I need to do API call to other application with this access token in header. That is why I need to be sure the token is still valid when I do the call .

For information I am using Generic type and I develop my custom provider. I am using Guard too.

**The expiration check and refresh token management is not fully managed by know/OAuth2 ?**

Thx in advance for your help

**Comment by kdefives** [comment]
Hello @weaverryan ,
Does knpuniverty/oauth2-client-bundle automatically manage and detect if the access token have to be refreshed? In that case, if token need to be refresh, we could imagine knpuniverty/oauth2-client-bundle could refresh the token automatically?

Or do I have to manage that part myself, on my application ? For instance using Events / EventsListeners using Symfony?

Thx

**Comment by ndench** [comment]
Hey @kdefives I have the same issue where I want an easy way to refresh the access token.

This bundle just uses league/oauth2-client under the hood, so you can see how to refresh a token from [their documentation](https://github.com/thephpleague/oauth2-client/blob/419d163a02654305773e07731dc26ce7528a574f/docs/usage.md#refreshing-a-token). To refresh within the context of this bundle, you can do:

```php
$provider = $clientRegistry->getClient('your client name')->getOAuth2Provider();

$existingAccessToken = getAccessTokenFromYourDataStore();

if ($existingAccessToken->hasExpired()) {
    $newAccessToken = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $existingAccessToken->getRefreshToken()
    ]);

    // Purge old access token and store new access token to your data store.
}
```

IMO I think this bundle should natively support refreshing the token. The reason that it doesn't is because the `authorization_code` grant type is hard coded into [OAuth2Client::getAccessToken](https://github.com/knpuniversity/oauth2-client-bundle/blob/73e8f09d733309726df7f6f00e18b4522a6a499f/src/Client/OAuth2Client.php#L110).

I'm not sure on the best way to add this feature, maybe @weaverryan could comment? I have a couple of ideas:
1. Make `grantType` a parameter to the `getAccessToken` method (it would have to be an optional second parameter with a default value to protect BC).
2. Make a new `refreshToken` method.

I prefer option 2, it doesn't risk BC and makes for a clearer API. However I'm unsure if it requires any of the "stateless" logic in the getAccessToken method.

**Comment by kdefives** [comment]
@ndench Thx for information!

Yes, your suggested code is what i am doing today to cover this need. As i have to check the token validity on every request, i plan to use http kernel component with event kernel controller : https://symfony.com/doc/current/event_dispatcher/before_after_filters.html#before-filters-with-the-kernel-controller-event

By using this solution, i will be able to execute my code to check the token validate and refresh it if needed.

I agreee that if knpuniversity/oauth2-client-bundle can manage that natively, if could be useful! 👍

**Comment by weaverryan** [comment]
Hey @ndench!

Thanks for the clear explanation of how you're handling things - that will definitely help others :).

> IMO I think this bundle should natively support refreshing the token.

I would be cool with having something like that :).

> I prefer option 2, it doesn't risk BC and makes for a clearer API. However I'm unsure if it requires any of the "stateless" logic in the getAccessToken method.

Yea, option 2 seems better to me at first also. I don't believe the refresh token would require any of the "stateless" logic. We can simply not use it in a new `refreshToken()` method.

Let me know if you have any other questions or thoughts :).

Cheers!

**Comment by ndench** [comment]
Thanks for the comments @weaverryan, I've submitted a quick pull request for this.
