### ISSUE TITLE
How to configure client_id and client_secret?

### ISSUE THREAD

**Issue by enumag** [knpuniversity/oauth2-client-bundle#267]
The recommended way from the documentation is to have them in ENV variables. Unfortunately this is not an option in my case - I have them available in database instead. How can I configure my provider in this case?

**Comment by bocharsky-bw** [comment]
Hm, I wonder how you configure other bundles with values from the database? I suppose you should do something similar in this case as well. :)

Could you take a look at this solution: https://stackoverflow.com/questions/28713495/how-to-load-symfonys-config-parameters-from-database-doctrine - does it works for you?

**Comment by enumag** [comment]
It doesn't. The values aren't in the database when the container is compiled.

**Comment by weaverryan** [comment]
Hey @enumag!

I would probably write a custom environment processor. Basically, the super power of the environment variable system is that it allows values to be read dynamically from the container instead of written to the container. Environment variables are "meant" to read... environment variables of course :). But there is no reason that you couldn't read "environment variables" from some other source (like a database) - here are the docs on the topic - https://symfony.com/doc/current/configuration/env_var_processors.html

So, for example, you might have something in config like this:

```yml
client_secret: %env(database:OAUTH_FACEBOOK_SECRET)%
```

Then you'd create a custom `database` env var processor to look this up in the database. The only "odd" part is that this will literally look up the `OAUTH_FACEBOOK_SECRET` env var FIRST, and then pass that value to your custom processor. So you'll probably need something silly like this:

```
parameters:
    # make sure the env var is set... and just set it to itself... this is the string your processor will receive
    env(OAUTH_FACEBOOK_SECRET): 'OAUTH_FACEBOOK_SECRET'
```

This is an ugly part basically... because we're abusing the env var system.

AND, finally. The true, non-hacky answer is this: don't use this bundle and register the "provider" services you need manually using a factory service. The factory would have access to the database and could look up the values and pass them when creating the provider(s).

I hope that helps!

Cheers!

**Comment by naumanafzal0313** [comment]
Hi @weaverryan  can you please explain this? 

The true, non-hacky answer is this: don't use this bundle and register the "provider" services you need manually using a factory service. The factory would have access to the database and could look up the values and pass them when creating the provider(s).

**Comment by steveWinter** [comment]
Just a shoutout to @weaverryan who has once again and come through with the details I needed to solve a problem I was having :-)

I've gone with something of a hybrid of your non-hacky solution - I've kept the bundle to provide a bunch of useful interfaces and classes but added my own service which can generate the 'Client' object needed with data from the DB.
