### ISSUE TITLE
Can I redirect the user to facebook native mobile app instead of the browser

### ISSUE THREAD

**Issue by bamgit** [knpuniversity/oauth2-client-bundle#286]
Hi,
Is there a way to be able to redirect my users website to the native facebook App (instead of the browser) in order to get connected.. I want this because when using the native FB app the user is already connected so he doesn't have to enter his username and password.. (some users will think this is a fake page to steal their accounts...) and they will leave..
It would be perfect if there is a way to do so

Thanks!

**Comment by weaverryan** [comment]
Hi!

I have no idea if this is possible. It *is* possible if you're building a native app, but I have no idea if it's possible from a web context like this. If it were (I can't find any info on it), I imagine it would involve redirecting to a `fb://` protocol when starting the process so that the app loads.

Cheers!
