### ISSUE TITLE
Wrong redirectUrl when enabling DoctrineExtensionsBundle

### ISSUE THREAD

**Issue by sgasser** [knpuniversity/oauth2-client-bundle#30]
Hi,

first great bundle @weaverryan. Thank you.

After installing your oauth2-client-bundle everything works.

If I add stof/doctrine-extensions-bundle and enable it, the generated redirectUrl of facebook is always http://localhost also on dev with localhost:8000 and in production.

I made a new symfony 3.1.1 installation to reproduce the problem: https://github.com/sgasser/oauth2-client-bundle-doctrine-extensions-bundle

Steps to reproduce:
1. ```git clone https://github.com/sgasser/oauth2-client-bundle-doctrine-extensions-bundle```
2. ```composer install```
3. ```php bin/console server:start```
4. open http://localhost:8000/connect/facebook
5. Redirects to http://localhost
6. Delete stof_doctrine_extensions in config.yml
7. open http://localhost:8000/connect/facebook
8. Redirects correctly to http://localhost:8000

Any idea?

Some strange problem with the router?

Thanks

**Comment by weaverryan** [comment]
Hi @sgasser!

Wow, that's craziness! And I wouldn't believe it, except that you made it very easy to repeat locally - thank you for that!

So, the problem is the Blameable functionality from the StofDoctrineExtensionBundle. Normally, when your OAuth2 client is created, we generate the redirectUrl using the `router` service. But, when the Blameable functionality is activated, it registers a listener *very* early on in Symfony. This listener causes the entire security system to boot up (probably something that could honestly be improved in Symfony's core), which in turn causes your OAuth2 client service to be instantiated (because it's a dependency of your authenticator). At this moment, the `router` service is used to generate the redirect_uri.

So what's the problem? The security system was booted up SO early, that the `RouterListener` hasn't executed yet. This is the listener that is responsible for telling the router "context" information, like the host name and HTTP port. Since that hasn't happened yet, it's still using the default `localhost` port `80`.

In my view, the bug is actually with Symfony's core - which over-eagerly loads the entire security system. But, there's a simple workaround: inject the entire Container into your `FacebookAuthenticator` instead of injecting your `FacebookClient`. Then, only later when you need it (i.e. `getCredentials()`), fetch it directly from the container. This will "decouple" your `FacebookClient` from the security layer so that it's not instantiated too early.

Phew! So that's an ugly guy, but let me know if you can get the workaround... working :).

Cheers!

**Comment by sgasser** [comment]
Hi @weaverryan,

thanks for your answer.

The workaround works great!

Thank you

**Comment by weaverryan** [comment]
Great - thanks for the update!
