### ISSUE TITLE
getCredentials must not be null

### ISSUE THREAD

**Issue by bettinz** [knpuniversity/oauth2-client-bundle#312]
Hello, I've opened an issue with integration of ADFS and this bundle.
Have anyone used this integrations? Can you help me to understand what I'm doing wrong?

The error is:

```
The return value of "Alancting\OAuth2\OpenId\Client\Security\Authenticator\AdfsAuthenticator::getCredentials()" must not be null. Return false from "Alancting\OAuth2\OpenId\Client\Security\Authenticator\AdfsAuthenticator::supports()" instead.
```

https://github.com/alancting/oauth2-microsoft-openid/issues/6

Thanks 🙏

**Comment by weaverryan** [comment]
Hi!

I'm not sure, but I would look / add some debugging here: https://github.com/alancting/oauth2-microsoft-openid/blob/19fb880e892af78ad7fa8042c251101450f282db/src/Security/Authenticator/AbstractMicrosoftAuthenticator.php#L44-L54

It seems that the `$oAuthCredential` ends up being null/false... so the property is never set on the next line (this property is eventually returned in `getCredentials()`, so the problem is that this property is null). But then the `_route` later probably matches what it should, so `supports()` returns true.

Good luck!

**Comment by bettinz** [comment]
Thanks @weaverryan 
in fact I've tried some debugging and the issue is `$oAuthCredential` empty.
I don't have the skills to dig into the code to understand why it's empty; I've asked here because maybe it's a configuration mistake or because the knpu_oauth2 and this plugin are not compatible right now.
The routes matches so I really can't find what is wrong; btw thanks for the help ;)

**Comment by bettinz** [comment]
Just to update, in the end I've used this one :-)
https://github.com/b3-it/oauth2-adfs
