### ISSUE TITLE
Where is knpu_oauth2_client.yaml after install?

### ISSUE THREAD

**Issue by wokalove** [knpuniversity/oauth2-client-bundle#324]
I installed this oauth and I don't have  knpu_oauth2_client.yaml in config/packages.

I assumed that it is required from readme from [Step 2](https://github.com/knpuniversity/oauth2-client-bundle#step-2-configure-the-provider)

I have just:
![image](https://user-images.githubusercontent.com/64095660/125131913-db941a80-e103-11eb-90cb-479fd230ff5f.png)

Should it be added manually or readme is not updated and it is solved in some other way? 
I tried manually, but then I have errrors that my server can't handle it. Any ideas?

Thanks in advance for your time ;)

**Comment by bocharsky-bw** [comment]
Hey @wokalove ,

Yeah, that file should be created automatically, as you can see from the contrib recipe: https://github.com/symfony/recipes-contrib/blob/e1b904c158f8813cb3d4c32ab22c648c8689dc00/knpuniversity/oauth2-client-bundle/1.20/config/packages/knpu_oauth2_client.yaml since v1.20 of the bundle. When you install the bundle with Composer - it might ask you if you want to run the conrib recipe or no, depends on your configuration, and you had to answer "yes" - only then the file would be created.

But it's not so important, you can easily create that file manually and copy/paste its content from the recipe I linked above.

However, if you tried to create that file manually and failed with that "server can't handle it" error - please, double-check that you don't have any misprints in keys, better to copy/paste the content from the recipe and try again. If still the same error - most probably you didn't install the bundle at all :) Try to install the bundle again with Composer and looks closer the output to know if that was successful

I hope this helps! :)

**Comment by wokalove** [comment]
Thank you @bocharsky-bw ! 
I reinstalled bundle, created manually this file and seems to work. Thank you for your time :)

**Comment by bocharsky-bw** [comment]
Awesome! I'm glad to hear it works for you now :)
