### ISSUE TITLE
works fine on local but got 403 error on prod

### ISSUE THREAD

**Issue by HysteriaKa** [knpuniversity/oauth2-client-bundle#367]
i usually found answers here without asking but not this time ! I am using symfony 5.4 php 8.1.0. I  it works fine on local. We host it in Plesk obsidian os Debian server 18.0.42. I got 403 error after picking a google account. I added the cacert.pem on server and filled the php.ini, i added the domain in google/dev but still having this 403 ! I don't know what else to do !!

**Comment by bocharsky-bw** [comment]
Hey @HysteriaKa ,

Hm, difficult to say. If I'm correct, you had to create a google app in the Google dashboard where you had to set a target URL to your website. Could you double-check it? It might be so that you're pointing to the local domain there, while you have to change the URL to the prod domain instead.

Otherwise, it's difficult to say, doesn't google say more context about this error except for just 403 status code? What is the content of the response? Is there any specific information in logs maybe?

**Comment by HysteriaKa** [comment]
Hey, thanks for trying to help me!  Yes i did add the domain on google/dev with the good Uri to prod domain.
We checked the logs and it says it's about setRule but we don't know what to do.
This is the log without our UrI : 

SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES_NAMES:scarab.profile|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@pmf bl_os_files" \ "id:210580,msg:'COMODO WAF: os File Access Attempt||%{tx.domain}|%{tx.mode}|2',phase:2,capture,block,setvar:'tx.points=+%{tx.points_limit4}',logdata:'Matched Data: ${Tx.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',t:none,t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase,rev:2,severity:2,tag:'CWAF',tag:'Other'"

**Comment by HysteriaKa** [comment]
Hey ! my co worker found how to do it !!

i put the solution for anyone that may need it : 

SecRule ARGS:scope "@contains https://www.googleapis.com/auth/userinfo.profile" "id:'9000000',phase:2,t:none,t:lowercase,pass,nolog,ctl:ruleRemoveById=*******"

**Comment by bocharsky-bw** [comment]
Great, thanks for sharing the solution with others!

**Comment by HysteriaKa** [comment]
Of course ! You  helped me by checking the logs !! it was all in !!

**Comment by gponty** [comment]
Hi @HysteriaKa 
I have same problem of you (ok in dev but 403 in prod)
Do you remember what you are updating to make this work?
Thank you !
