### ISSUE TITLE
It's possible to avoid the whole container injection in the ClientRegistry service?

### ISSUE THREAD

**Issue by giovkanata** [knpuniversity/oauth2-client-bundle#50]
I just discovered that the whole container is injected in the `ClientRegistry` service (to get dinamically the social client) and I saw in the docs: 
> CAUTION You can also inject the individual client (e.g. FacebookClient) into your authenticator instead of the ClientRegistry. However, this may cause ciricular reference issues and degrades performance (because autheticators are instantiated on every request, even though you rarely need the FacebookClient to be created). The ClientRegistry lazily creates the client objects.

but the `ClientRegistry` service it's not lazy loaded (lazy="true") and this means it will always be instantiated (and inflated with the whole container). I'm right? Can you suggest another approach on which I can work on?

PS: what do you think to add a new tag on StackOverflow for this bundle? It would be better for this type of questions, don't you? (I have only 1400 points 😆 )

**Comment by weaverryan** [comment]
Hey @giovkanata!

Ah, so you're correct that the `ClientRegistry` is not lazy loaded... but all of the *clients* inside of it *are* (because ClientRegistry doesn't instantiate them until [and if] they are needed). For example, if I create an authenticator and inject the FacebookClient directly, then the FacebookClient will be instantiated on every request (because authenticators are instantiated on every request). But if you instead inject the `ClientRegistry`, then the `ClientRegistry` is instantiated on every request, but your FacebookClient is *not* automatically instantiated: it will only be instantiated if/when your authenticator requests that client from the ClientRegistry. 

So, you don't need to do anything :) - just inject the ClientRegistry and your clients will be instantiated lazily. There is no need for lazy=true - injecting the container (like we've done) is another way to achieve the laziness.

I hope this helps!

P.S. Having a tag on StackOverflow makes sense to me! But I probably also don't have enough points, and I (unfortunately) won't check there for questions. But, the questions would get a lot more exposure from other people.

Cheers!

**Comment by curry684** [comment]
[url=http://stackoverflow.com/users/1729885/niels-keurentjes]Whatcha need?[/url] 😉 However I don't really find a lot of questions there related to this bundle, and I need at least one, preferably 5+, to create a tag.

**Comment by weaverryan** [comment]
Wow, nice! @giovkanata do you know of any existing questions about the bundle?

**Comment by giovkanata** [comment]
@weaverryan not at the moment, but if I'll see something I'll ping you here.
